update git pre-commit script

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -1,76 +1,53 @@
 #!/bin/sh
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
+printf "\e[33;1m%s\e[0m\n" 'Pre-Commit'
 
-result=$(flutter analyze --no-fatal-infos --no-fatal-warnings)
-exitCode=$? # If the exitCode is zero, then command executed successfully.
+# Undo the stash of the files
+pop_stash_files () {
+    if [ -n "$hasChanges" ]; then
+        printf "\e[33;1m%s\e[0m\n" '=== Applying git stash changes ==='
+        git stash pop
+    fi
+}
 
-if [ $exitCode  -ne 0 ]; then
-  echo "$result"
-  echo "Flutter analyze found issues, please fix them."
+# Stash unstaged files
+hasChanges=$(git diff)
+if [ -n "$hasChanges" ]; then
+    printf "\e[33;1m%s\e[0m\n" 'Stashing unstaged changes'
+    git stash push --keep-index
+fi
+
+# Dart fix
+printf "\e[33;1m%s\e[0m\n" '=== Running Dart Fix ==='
+dart fix --apply
+printf "\e[32;1m%s\e[0m\n" 'Finished running Dart Fix'
+printf '%s\n' "${avar}"
+
+# Flutter Analyzer
+printf "\e[33;1m%s\e[0m\n" '=== Running Flutter analyzer ==='
+flutter analyze
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" '=== Flutter analyzer error ==='
+  pop_stash_files
   exit 1
 fi
-echo "Finished running flutter analyze command."
+printf "\e[32;1m%s\e[0m\n" 'Finished running Flutter analyzer'
+printf '%s\n' "${avar}"
 
-################################################################
-
-# 2. Run `dart dry --apply` to auto-fix basic issues.
-result=$(dart fix --apply)
-exitCode=$?
-
-# Adding the files updated by `dart fix` command to git.
-git add .
-
-echo "$result"
-
-if [ $exitCode -ne 0 ]; then
-  echo "dart fix command failed to execute."
+# Unit tests
+printf "\e[33;1m%s\e[0m\n" '=== Running Very Good Unit and Widget Tests ==='
+flutter test --coverage --test-randomize-ordering-seed random
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" '=== Unit tests error ==='
+  pop_stash_files
   exit 1
 fi
-echo "Finished running dart fix command."
+printf "\e[32;1m%s\e[0m\n" 'Finished running Very Good Unit and Widget Tests'
+printf '%s\n' "${avar}"
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
+hasNewFilesFormatted=$(git diff)
+if [ -n "$hasNewFilesFormatted" ]; then
+    git add .
+    printf "\e[32;1m%s\e[0m\n" 'Formated files added to git stage'
 fi
 
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --type=bool hooks.allownonascii)
-
-# Redirect output to stderr.
-exec 1>&2
-
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
-	exit 1
-fi
-
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+pop_stash_files
