disabled run unit test phase on git pre commit

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -34,15 +34,15 @@ printf "\e[32;1m%s\e[0m\n" 'Finished running Flutter analyzer'
 printf '%s\n' "${avar}"
 
 # Unit tests
-printf "\e[33;1m%s\e[0m\n" '=== Running Very Good Unit and Widget Tests ==='
-flutter test --coverage --test-randomize-ordering-seed random
-if [ $? -ne 0 ]; then
-  printf "\e[31;1m%s\e[0m\n" '=== Unit tests error ==='
-  pop_stash_files
-  exit 1
-fi
-printf "\e[32;1m%s\e[0m\n" 'Finished running Very Good Unit and Widget Tests'
-printf '%s\n' "${avar}"
+# printf "\e[33;1m%s\e[0m\n" '=== Running Very Good Unit and Widget Tests ==='
+# flutter test --coverage --test-randomize-ordering-seed random
+# if [ $? -ne 0 ]; then
+#   printf "\e[31;1m%s\e[0m\n" '=== Unit tests error ==='
+#   pop_stash_files
+#   exit 1
+# fi
+# printf "\e[32;1m%s\e[0m\n" 'Finished running Very Good Unit and Widget Tests'
+# printf '%s\n' "${avar}"
 
 hasNewFilesFormatted=$(git diff)
 if [ -n "$hasNewFilesFormatted" ]; then
